name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            AUTH_HEADER_VALUE
            NOTION_API_KEY
        env:
          AUTH_HEADER_VALUE: ${{ secrets.AUTH_HEADER_VALUE }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}

